# Generated by Django 5.2.14 on 2026-05-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='menucategory',
            new_name='restaurants_restaur_d4034f_idx',
            old_name='restaurants__restaur_2e2f8a_idx',
        ),
        migrations.RenameIndex(
            model_name='menucategory',
            new_name='restaurants_restaur_1963bc_idx',
            old_name='restaurants__restaur_9a1c2b_idx',
        ),
        migrations.RenameIndex(
            model_name='menuitem',
            new_name='restaurants_restaur_1087ee_idx',
            old_name='restaurants__restaur_4d5e6f_idx',
        ),
        migrations.RenameIndex(
            model_name='menuitem',
            new_name='restaurants_categor_33aa85_idx',
            old_name='restaurants__categor_7g8h9i_idx',
        ),
        migrations.RenameIndex(
            model_name='restaurant',
            new_name='restaurants_is_acti_ca2bee_idx',
            old_name='restaurants__is_acti_8f0b0d_idx',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='opening_hours',
            field=models.CharField(blank=True, help_text='Human-readable hours, e.g. Mon–Sun 09:00–22:00', max_length=255),
        ),
    ]
