# Generated by Django 5.2.14 on 2026-05-19 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver_acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='When the assigned driver acknowledged the manual assignment (no status change).', null=True),
        ),
        migrations.CreateModel(
            name='DriverDeliveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('acknowledged', 'Acknowledged'), ('picked_up', 'Picked up'), ('started_delivery', 'Started delivery'), ('completed', 'Completed')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_events', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_events', to='orders.order')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['order', '-created_at'], name='orders_driv_order_i_81706a_idx')],
            },
        ),
    ]
