# Generated by Django 5.2.14 on 2026-05-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_declined_status'),
        ('orders', '0004_order_searching_driver_status'),
    ]

    operations = [
    ]
