# Generated by Django 5.2.14 on 2026-05-20 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_custome_a935a8_idx',
            old_name='payments_pa_custome_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_order_i_a76289_idx',
            old_name='payments_pa_order_i_idx',
        ),
    ]
