"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys
from datetime import timedelta
import dj_database_url
from django.core.exceptions import ImproperlyConfigured

try:
    from dotenv import load_dotenv
except ImportError:
    load_dotenv = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

IS_RENDER = os.getenv("RENDER", "").strip().lower() == "true"
IS_MANAGED_RUNTIME = IS_RENDER or bool(os.getenv("PORT"))

if load_dotenv and not IS_MANAGED_RUNTIME and (BASE_DIR / ".env").exists():
    load_dotenv(BASE_DIR / ".env")


def env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_int(name: str, default: int) -> int:
    value = os.getenv(name)
    if value is None:
        return default
    return int(value.strip())


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

DEBUG = env_bool("DEBUG", default=False)

SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "django-insecure-dev-only-key"
    else:
        raise ImproperlyConfigured(
            "SECRET_KEY environment variable is required when DEBUG is False"
        )

ALLOWED_HOSTS = [host.strip() for host in os.getenv("ALLOWED_HOSTS", "").split(",") if host.strip()]
if DEBUG and not ALLOWED_HOSTS:
    # 10.0.2.2 is the Android emulator alias for the host machine loopback.
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "10.0.2.2"]
# Physical phones hit the API via LAN IP; allow any Host in local DEBUG only.
if DEBUG and "*" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS = [*ALLOWED_HOSTS, "*"]
if not DEBUG and not ALLOWED_HOSTS:
    raise ImproperlyConfigured(
        "ALLOWED_HOSTS must be set via environment when DEBUG is False"
    )

if env_bool("BEHIND_REVERSE_PROXY", default=not DEBUG):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "apps.users.apps.UsersConfig",
    "apps.drivers.apps.DriversConfig",
    "apps.restaurants.apps.RestaurantsConfig",
    "apps.orders.apps.OrdersConfig",
    "apps.payments.apps.PaymentsConfig",
    "apps.analytics.apps.AnalyticsConfig",
    "core.apps.CoreConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.getenv("DATABASE_URL")
DB_SSL_REQUIRE = env_bool("DB_SSL_REQUIRE", default=not DEBUG)

if IS_MANAGED_RUNTIME and DATABASE_URL and "@db:" in DATABASE_URL:
    raise ImproperlyConfigured(
        "DATABASE_URL points to Docker host 'db'. Set DATABASE_URL to your managed Postgres URL."
    )

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=DB_SSL_REQUIRE,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Local `manage.py test` should not require Docker Postgres when DATABASE_URL targets compose hostnames.
if any(arg == "test" for arg in sys.argv):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": ":memory:",
        }
    }

# Cache: Redis for DRF throttling across Gunicorn workers (LocMem in unit tests only).
if any(arg == "test" for arg in sys.argv):
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }
else:
    _redis_cache_url = (os.getenv("REDIS_CACHE_URL") or "").strip()
    if _redis_cache_url:
        CACHES = {
            "default": {
                "BACKEND": "django.core.cache.backends.redis.RedisCache",
                "LOCATION": _redis_cache_url,
            }
        }
    else:
        # Fallback avoids 500s on throttled endpoints when Redis is not provisioned.
        CACHES = {
            "default": {
                "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            }
        }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
# Ensure upload directory exists (logo/cover/menu images).
os.makedirs(MEDIA_ROOT, exist_ok=True)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "core.User"

# CORS (Next.js dashboard + mobile web; architecture: explicit origins in production)
def _ensure_scheme(origin: str) -> str:
    """Add http:// or https:// scheme if missing."""
    origin = origin.strip()
    if not origin:
        return origin
    if origin.startswith(("http://", "https://")):
        return origin
    return f"https://{origin}" if not DEBUG else f"http://{origin}"

_cors_raw = os.getenv("CORS_ALLOWED_ORIGINS", "")
CORS_ALLOWED_ORIGINS = [_ensure_scheme(o) for o in _cors_raw.split(",") if o.strip()]
if DEBUG and not CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS = [
        "http://127.0.0.1:3000",
        "http://localhost:3000",
        "https://backendproviderkech.onrender.com"
    ]

CORS_ALLOW_CREDENTIALS = env_bool("CORS_ALLOW_CREDENTIALS", default=True)

# HTTPS / cookies (admin session + CSRF). Enable in production behind TLS.
if DEBUG:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
else:
    SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", default=True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

CSRF_TRUSTED_ORIGINS = list(CORS_ALLOWED_ORIGINS)

# API auth: JWT default; require auth unless a view sets AllowAny (architecture: RBAC at DRF).
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "apps.users.authentication.SafeJWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "apps.users.api.exceptions.auth_safe_exception_handler",
    "DEFAULT_THROTTLE_RATES": {
        "auth_token": os.getenv("THROTTLE_AUTH_TOKEN", "60/hour"),
        "auth_refresh": os.getenv("THROTTLE_AUTH_REFRESH", "120/hour"),
        "auth_verify": os.getenv("THROTTLE_AUTH_VERIFY", "120/hour"),
        "auth_register": os.getenv("THROTTLE_AUTH_REGISTER", "20/hour"),
        "auth_admin_create_sales": os.getenv("THROTTLE_AUTH_ADMIN_CREATE_SALES", "120/hour"),
        "auth_logout": os.getenv("THROTTLE_AUTH_LOGOUT", "60/hour"),
        "auth_staff": os.getenv("THROTTLE_AUTH_STAFF", "200/hour"),
        "auth_otp_send": os.getenv("THROTTLE_AUTH_OTP_SEND", "10/hour"),
        "auth_otp_verify": os.getenv("THROTTLE_AUTH_OTP_VERIFY", "30/hour"),
        "auth_driver_onboarding": os.getenv("THROTTLE_AUTH_DRIVER_ONBOARDING", "120/hour"),
    },
}

if DEBUG:
    _jwt_rotate = env_bool("JWT_ROTATE_REFRESH_TOKENS", False)
    _jwt_blacklist_after = env_bool("JWT_BLACKLIST_AFTER_ROTATION", False)
else:
    _jwt_rotate = env_bool("JWT_ROTATE_REFRESH_TOKENS", True)
    _jwt_blacklist_after = env_bool("JWT_BLACKLIST_AFTER_ROTATION", True)

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=env_int("JWT_ACCESS_TOKEN_MINUTES", 60)),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=env_int("JWT_REFRESH_TOKEN_DAYS", 7)),
    "ROTATE_REFRESH_TOKENS": _jwt_rotate,
    "BLACKLIST_AFTER_ROTATION": _jwt_blacklist_after,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Kech Delivery API",
    "VERSION": "1.0.0",
    "DESCRIPTION": "REST API for Kech Delivery (auth and platform services).",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "APPEND_COMPONENTS": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            }
        }
    },
    "SECURITY": [{"bearerAuth": []}],
}

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://localhost:6379/1")

# When True, GET /ready pings Redis (broker URL). Disable in dev/test if Redis is not running.
READINESS_CHECK_REDIS = env_bool("READINESS_CHECK_REDIS", default=not DEBUG)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"

# Chapa payment gateway (never commit real keys)
CHAPA_SECRET_KEY = os.getenv("CHAPA_SECRET_KEY", "")
CHAPA_PUBLIC_KEY = os.getenv("CHAPA_PUBLIC_KEY", "")
CHAPA_WEBHOOK_SECRET = os.getenv("CHAPA_WEBHOOK_SECRET", "")
CHAPA_CALLBACK_URL = os.getenv("CHAPA_CALLBACK_URL", "")
# Legacy CHAPA_RETURN_URL: deep link (kechdelivery://…) or https URL for Chapa return_url.
_chapa_return_env = os.getenv("CHAPA_RETURN_URL", "").strip()
if _chapa_return_env.startswith(("http://", "https://")):
    CHAPA_RETURN_HTTP_URL = os.getenv("CHAPA_RETURN_HTTP_URL", _chapa_return_env).rstrip("/")
    CHAPA_APP_RETURN_URL = os.getenv(
        "CHAPA_APP_RETURN_URL", "kechdelivery://payment/return"
    ).rstrip("/")
else:
    CHAPA_APP_RETURN_URL = os.getenv(
        "CHAPA_APP_RETURN_URL", _chapa_return_env or "kechdelivery://payment/return"
    ).rstrip("/")
    CHAPA_RETURN_HTTP_URL = os.getenv("CHAPA_RETURN_HTTP_URL", "").rstrip("/")
CHAPA_CURRENCY = os.getenv("CHAPA_CURRENCY", "ETB")
# Chapa rejects some domains (e.g. kechdelivery.app); use a domain their API accepts.
CHAPA_CUSTOMER_EMAIL_DOMAIN = os.getenv("CHAPA_CUSTOMER_EMAIL_DOMAIN", "ethionet.et").strip().lstrip("@")
CHAPA_MOCK_MODE = env_bool("CHAPA_MOCK_MODE", default=DEBUG and not CHAPA_SECRET_KEY)
# Base URL reachable from the mobile app (emulator: http://10.0.2.2:8000). Used for mock checkout HTML.
CHAPA_PUBLIC_BASE_URL = os.getenv("CHAPA_PUBLIC_BASE_URL", "http://127.0.0.1:8000").rstrip("/")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "kech.auth": {
            "handlers": ["console"],
            "level": os.getenv("AUTH_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "kech.payments": {
            "handlers": ["console"],
            "level": os.getenv("PAYMENTS_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
    },
}
