# Generated by Django 5.2.12 on 2026-03-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
