# Generated by Django 5.2.14 on 2026-05-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_driver_onboarding_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='operational_status',
            field=models.CharField(choices=[('offline', 'Offline'), ('online', 'Online'), ('busy', 'Busy')], db_index=True, default='offline', max_length=16),
        ),
    ]
